### Tensors

In [1]:
import tensorflow as tf

In [2]:
X = tf.constant([[1, 2], [4, 7]])
X

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 7]])>

In [9]:
tf.reshape(X, shape=(4, -1))

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [2],
       [4],
       [7]])>

In [4]:
X

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 7]])>

In [6]:
numpy = X.numpy()
numpy

array([[1, 2],
       [4, 7]])

In [12]:
X.shape, tf.size(X), X.dtype, X.ndim

(TensorShape([2, 2]), <tf.Tensor: shape=(), dtype=int32, numpy=4>, tf.int32, 2)

In [14]:
ones = tf.ones(shape=(2, 2))
zeros = tf.zeros(shape=(2, 2))
ones, zeros

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0., 0.],
        [0., 0.]], dtype=float32)>)

In [16]:
ones_like =tf.ones_like(X)
zeros_like = tf.zeros_like(X)
ones_like, zeros_like

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 1],
        [1, 1]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[0, 0],
        [0, 0]])>)

In [21]:
eye = tf.eye(3)
eye

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

### Creating random constant tensors

In [23]:
X1 = tf.random.normal(shape=(2,2), mean=0. ,stddev=1)
X1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.6894172, -0.1225363],
       [ 0.8390331,  0.5656439]], dtype=float32)>

In [27]:
X2 = tf.random.uniform(shape=(3,), minval=0, maxval=5, dtype=tf.int32)
X2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 1])>

#### Variables
>Variables are special tensors used to store mutable state (such as the weights of a neural network). 

In [28]:
a = tf.Variable([2, 3, 4, 5.])
a

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([2., 3., 4., 5.], dtype=float32)>

In [30]:
a.assign([2, 3, 5,2])
a

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([2., 3., 5., 2.], dtype=float32)>

### Gradients
>Here's another big difference with NumPy: you can automatically retrieve the gradient of any differentiable expression.

> Just open a GradientTape, start "watching" a tensor via tape.watch(), and compose a differentiable expression using this tensor as input:

In [32]:
a = tf.random.normal(shape=(2, 2))
b = tf.random.normal(shape=(2, 2))

with tf.GradientTape() as tape:
    tape.watch(a) # Start recording the history of operations applied to `a`
    c = tf.sqrt(tf.square(a) + tf.square(b))  # Do some math using `a`
    # What's the gradient of `c` with respect to `a`?
    dc_da = tape.gradient(c, a)
dc_da 

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.7364066 ,  0.72710776],
       [ 0.61761653, -0.86808693]], dtype=float32)>

> By default, variables are watched automatically, so you don't need to manually watch them:

### Keras layers
> While TensorFlow is an infrastructure layer for differentiable programming, dealing with tensors, variables, and gradients, Keras is a user interface for deep learning, dealing with layers, models, optimizers, loss functions, metrics, and more.

> Keras serves as the high-level API for TensorFlow: Keras is what makes TensorFlow simple and productive.

> The Layer class is the fundamental abstraction in Keras. A Layer encapsulates a state (weights) and some computation (defined in the call method).

In [47]:
"""y = mx+ c"""
from tensorflow.keras.layers import Layer

class Linear(Layer):
    def __init__(self, units=32, input_dim=32):
        super(Linear, self).__init__()
        w_init = tf.random_normal_initializer()
        self.w = tf.Variable(
            initial_value = w_init(shape=(input_dim, units), dtype = tf.float32)
            , trainable = True
        )
        b_init = tf.zeros_initializer()
        self.b = tf.Variable(
            initial_value = b_init(shape=(units, ) ,dtype = tf.float32)
        )
    def call(self, inputs):
        return tf.matmul(inputs, self.w) + self.b
    pass

In [52]:
linear_layer = Linear(units=4, input_dim=2)
print(linear_layer)
y = linear_layer(tf.ones((2, 2)))
print(y)
y.shape == (2, 4)

linear_layer.weights

tf.Tensor(
[[-0.03776359 -0.05652292  0.00890213 -0.03412773]
 [-0.03776359 -0.05652292  0.00890213 -0.03412773]], shape=(2, 4), dtype=float32)


[<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
 array([[-0.01761069, -0.04154172, -0.05200666,  0.01570257],
        [-0.0201529 , -0.0149812 ,  0.06090879, -0.04983031]],
       dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]