### Mean Absolute Error Loss
If we believe that the outliers just represent corrupted data, then we should choose **MAE** as loss. On the other hand If the outliers represent anomalies that are important for business and should be detected, then we should use **MSE**.
> This loss is fore **Regression tasks**

In [2]:
import tensorflow as tf

In [3]:
y = tf.constant([0.1, 1.2, 1.3, 1.4, 1.5, 1.6])
y_pred = tf.constant([0.1, 1.3, 1.3, 1.3, 1.7, 1.9])

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]], dtype=float32)>

### Calculating the ``MAE`` Error using TensorFloe.

In [3]:
loss = tf.keras.losses.MAE(y, y_pred)
loss

<tf.Tensor: shape=(), dtype=float32, numpy=0.11666665>

#### Calculating using tensorflow operation

In [4]:
loss = tf.reduce_mean(tf.abs(y-y_pred))
loss

<tf.Tensor: shape=(), dtype=float32, numpy=0.11666665>

### Creating a `mae` function

<p align="center">
    <img src="https://www.statisticshowto.com/wp-content/uploads/2016/10/MAE.png"/>
</p>

In [17]:
class Losses:
    def __init__(self):
        pass
    
    def mae(self, y_true, y_pred):
        return tf.reduce_mean(tf.abs(y-y_pred))
    
    def mae_(self, y_true, y_pred):
        return tf.reduce_sum(tf.abs(y_true-y_pred))/ y_true.shape[0]

In [13]:
criterion = Losses()
criterion.mae(y, y_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=0.11666665>

> We are getting the same loss as before.

In [18]:
criterion = Losses()
criterion.mae_(y, y_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=0.11666665>

> We are getting the same loss as well