### Mean Squared Error Loss.
If the outliers represent anomalies that are important for business and should be detected, then we should use **MSE**. On the other hand, if we believe that the outliers just represent corrupted data, then we should choose **MAE** as loss.
> This loss is fore **Regression tasks**

In [1]:
import tensorflow as tf

In [2]:
y = tf.constant([0.1, 1.2, 1.3, 1.4, 1.5, 1.6])
y_pred = tf.constant([0.1, 1.3, 1.3, 1.3, 1.7, 1.9])

### Tensorflow MSE Loss

In [4]:
loss = tf.keras.losses.MSE(y, y_pred)
loss

<tf.Tensor: shape=(), dtype=float32, numpy=0.024999997>

#### How to calculate it using tensorflow functions on tensors

In [9]:
loss =tf.reduce_mean(tf.square(y - y_pred))
loss

<tf.Tensor: shape=(), dtype=float32, numpy=0.024999997>

### Creating a ``MSE`` function
<img src="https://cdn-media-1.freecodecamp.org/images/hmZydSW9YegiMVPWq2JBpOpai3CejzQpGkNG"/>

In [29]:
class Loses:
    def __init__(self):
        pass
    
    def mse(self, y_true, y_pred):
        return tf.reduce_mean(tf.square(y_true-y_pred))
    
    def mse_(self, y_true, y_pred):
        return tf.reduce_sum((y-y_pred)**2)/y.shape[0]

In [30]:
loss_fn = Loses()
loss_fn.mse(y, y_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=0.024999997>

> We are still getting the same output

In [31]:
loss_fn.mse_(y, y_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=0.024999997>

> The results are still the same!!